repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-docstring-first
        stages:
        - commit
        - push
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
        stages:
        - commit
        - push
    -   id: requirements-txt-fixer
        stages:
          - commit
          - push
    -   id: end-of-file-fixer
        stages:
          - commit
          - push
    -   id: mixed-line-ending
        stages:
          - commit
          - push
    -   id: trailing-whitespace
        stages:
          - commit
          - push
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
        exclude: ^migration/
        stages:
        - commit
        - push
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages:
        - commit
        - push
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        files: 'src/.*'
        args: [--strict, --install-types]
        additional_dependencies: [mypy-extensions==0.4.3]
